version: '3.8'

services:
  expo-typescript:
    container_name: expo-typescript
    build: .
    volumes:
      - ./expo:/usr/src/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=${EXPO_DEVTOOLS_LISTEN_ADDRESS}
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    tty: true
